---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $.Values.apigee.env_group_host }}-certificate
  namespace: {{ $.Values.namespace }}
spec:
  isCA: false
  commonName: {{ $.Values.apigee.env_group_host }}
  secretName: {{ $.Values.ingress.tls.secret }}
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ $.Values.certmanager.issuer.name }}-ca-issuer
    kind: Issuer
    group: cert-manager.io