---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ $.Values.certmanager.issuer.name }}-selfsigned-issuer
  namespace: {{ $.Values.namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $.Values.certmanager.issuer.name }}-ca-certificate
  namespace: {{ $.Values.namespace }}
spec:
  isCA: true
  commonName: {{ $.Values.certmanager.issuer.name }}-ca
  secretName: {{ $.Values.certmanager.issuer.name }}-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ $.Values.certmanager.issuer.name }}-selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ $.Values.certmanager.issuer.name }}-ca-issuer
  namespace: {{ $.Values.namespace }}
spec:
  ca:
    secretName: {{ $.Values.certmanager.issuer.name }}-ca-secret
